import os
import csv
from datetime import datetime, timedelta, timezone
from extensions import celery_app, db
from models import User, StudentProfile, PlacementDrive, Application
from flask import current_app

def send_mock_email(to, subject, body):
    """Utility to simulate sending an email/webhook without real SMTP credentials"""
    print(f"\n--- MOCK EMAIL ---")
    print(f"To: {to}\nSubject: {subject}\nBody:\n{body}")
    print(f"------------------\n")

@celery_app.task
def daily_deadline_reminders():
    """Scheduled Job - Daily reminders for upcoming application deadlines"""
    now = datetime.now(timezone.utc)
    # Drives closing in next 48 hours
    upcoming_limit = now + timedelta(days=2) 
    
    closing_drives = PlacementDrive.query.filter(
        PlacementDrive.status == 'Approved',
        PlacementDrive.application_deadline > now,
        PlacementDrive.application_deadline <= upcoming_limit
    ).all()

    if not closing_drives:
        return "No upcoming deadlines."

    students = User.query.filter_by(role='Student', active_flag=True, blacklist_flag=False).all()
    
    for student in students:
        message = "Reminder: The following placement drives are closing soon:\n"
        for drive in closing_drives:
            message += f"- {drive.job_title} (Deadline: {drive.application_deadline.strftime('%Y-%m-%d')})\n"
        
        # Simulating Webhook/Email alert as required
        send_mock_email(to=student.username, subject="Upcoming Placement Deadlines", body=message)
        
    return "Daily reminders sent successfully."

@celery_app.task
def monthly_activity_report():
    """Scheduled Job - Monthly HTML Activity Report saved for Admin"""
    now = datetime.now(timezone.utc)
    first_day_of_month = now.replace(day=1, hour=0, minute=0, second=0, microsecond=0)
    
    # 1. Calculate stats
    drives_conducted = PlacementDrive.query.filter(PlacementDrive.created_at >= first_day_of_month).count()
    total_applied = Application.query.filter(Application.application_date >= first_day_of_month).count()
    total_selected = Application.query.filter(Application.application_date >= first_day_of_month, Application.status == 'Selected').count()

    # 2. Generate HTML Content (Requirement: Well-designed HTML/PDF Report)
    html_content = f"""
    <html>
    <head>
        <title>Monthly Activity Report</title>
        <style>
            body {{ font-family: Arial, sans-serif; margin: 40px; }}
            h2 {{ color: #2c3e50; }}
            .stats {{ border: 1px solid #ddd; padding: 20px; border-radius: 8px; background: #f9f9f9; }}
            li {{ margin-bottom: 10px; font-size: 16px; }}
        </style>
    </head>
    <body>
        <h2>Monthly Placement Activity Report</h2>
        <p><strong>Report Date:</strong> {now.strftime('%B %Y')}</p>
        <hr>
        <div class="stats">
            <ul>
                <li><strong>Number of Drives Conducted:</strong> {drives_conducted}</li>
                <li><strong>Number of Students Applied:</strong> {total_applied}</li>
                <li><strong>Number of Students Selected:</strong> {total_selected}</li>
            </ul>
        </div>
        <p><em>This is an automated report generated by the Placement Portal System.</em></p>
    </body>
    </html>
    """
    
    # 3. Save as a physical file so Admin can view/download it
    filename = f"Monthly_Report_{now.strftime('%Y_%m')}.html"
    filepath = os.path.join(current_app.config['BASE_DIR'], 'uploads', filename)
    
    with open(filepath, 'w') as f:
        f.write(html_content)

    # 4. Notify Admin (Mock Email)
    admin = User.query.filter_by(role='Admin').first()
    if admin:
        send_mock_email(to=admin.username, subject="Monthly Report Generated", body=f"Report saved at: {filename}")

    return f"Monthly report generated: {filename}"

@celery_app.task
def export_applications_csv(student_id, username):
    """User Triggered Async Job - Export Applications as CSV"""
    applications = Application.query.filter_by(student_id=student_id).all()
    
    # Using 'uploads' folder to store the generated CSV
    filename = f"export_{username}_{datetime.now().strftime('%Y%m%d%H%M%S')}.csv"
    filepath = os.path.join(current_app.config['BASE_DIR'], 'uploads', filename)
    
    with open(filepath, mode='w', newline='') as file:
        writer = csv.writer(file)
        writer.writerow(["Student ID", "Company Name", "Drive Title", "Application Status", "Date Applied"])
        
        for app in applications:
            # Safe traversal to avoid crashes if company/drive is deleted
            company_name = "Unknown"
            if app.drive:
                # Need to fetch company profile safely
                from models import CompanyProfile
                comp = CompanyProfile.query.filter_by(id=app.drive.company_id).first()
                if comp: company_name = comp.company_name
            
            drive_title = app.drive.job_title if app.drive else "N/A"
            
            writer.writerow([
                app.student_id, 
                company_name, 
                drive_title, 
                app.status, 
                app.application_date.strftime('%Y-%m-%d')
            ])

    # Send alert once done
    send_mock_email(
        to=username, 
        subject="Your Application History Export is Ready", 
        body=f"Your CSV export is complete. File saved at: {filepath}"
    )
    
    return f"Export completed for {username}."